# Source: cluster-api-aws/templates/machine-pool.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: cpq03imh8-mp-taco
  namespace: cpq03imh8
spec:
  clusterName: cpq03imh8
  replicas: 3
  template:
    metadata:
      labels:
            servicemesh: enabled
            taco-ingress-gateway: enabled
            taco-lma: enabled
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfig
          name: cpq03imh8-mp-taco
          namespace: cpq03imh8
      clusterName: cpq03imh8
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSMachinePool
        name: cpq03imh8-mp-taco
        namespace: cpq03imh8
      version: v1.22.5

